version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mongo
    environment:
      - FLASK_APP=app
      - FLASK_RUN_HOST=0.0.0.0
    command: flask run --host=0.0.0.0 --port=5000
  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
