version: '3.8'

services:
  api:
    build: .
    container_name: leaderboard-api-api
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0
  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  test:
    build: .
    container_name: leaderboard_test
    environment:
      - FLASK_ENV=testing
    command: python -m unittest discover tests
    depends_on:
      - mongo
    volumes:
      - .:/app

volumes:
  mongo-data:
